#ifndef SMDFILEFORMAT_GLOBAL_H
#define SMDFILEFORMAT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SMDFILEFORMAT_LIBRARY)
#  define SMDFILEFORMATSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SMDFILEFORMATSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SMDFILEFORMAT_GLOBAL_H
